apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    name: debug
    project: roboshop
spec:
  containers:
  - name: debug
    image: dockerfilelinux/debug:v1
    imagePullPolicy: Always  # it means take latest changes always vunte it will take for run debug container always