
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: dockerfilelinux/mongodb:v1  # comes from HUB
        imagePullPolicy: Always 
      # readiness probe
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10     # every 10 seconds ki checks 
      # liveness probe 
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15  # based on app and project requirment 
          periodSeconds: 15


# Service code bcz cata will connect to mongodb so for that we need set up service file 
apiVersion: v1
kind: Service
metadata:
  name: mongodb # ikkada name DNS ga cata lo config map lo use avuthuni 
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017 # service port  # for no confusion kosam we have to given same ports
      targetPort: 27017 # container port