
#sess 71

# Configuration code for dependecies
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:  # so this the file for mysql data ni read kosam 
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---
# mysql basic code 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec:
      serviceAccount: secret-mysql-reader
      initContainers:
      - name: init-fetch-secreate
        image: amazon/aws-cli
        command: 
        - sh
        - -c
        - |
          aws secretsmanager get-secret-value --secret-id roboshop/dev/mysql_password --query 'SecretString' --output text | jq -r '.["mysql-password"]' >/tmp/mysql-root-password.txt
        volumeMounts:        # these volume for container level access
        - name: mysql-secrets
          mountPath: /tmp
      containers:
      - name: mysql
        image: dockerfilelinux/mysql:v2
        imagePullPolicy: Always
        
        volumeMounts:        # these volume for container level access
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        - name: mysql-secrets
          mountPath: /tmp
      volumes:  # these volume for POD level acess
        - name: mysql-config
          configMap:
            name: mysql
        - name: mysql-secrets
          emptyDir: {}   # it means temporary storage 

